### ISSUE TITLE
Frontend 

### ISSUE THREAD

**Issue by MinecraftPublisher** [mhnasajpour/Mask#1]
Is a frontend required for this project?

**Comment by MinecraftPublisher** [comment]
I can write a pure html css js website for this website with custom css and a javascript api wrapper for the program. As the site will be static, Hosting is possible via the same infrastructure as the backend.

**Comment by mhnasajpour** [comment]
Hi Martia. Yes, you can definitely do it, but doing this project by me was just to increase my skills and experiences in backend and there was no other intention behind this.
You can design a frontend for this as a practice and contribute in my project.
I will very glad to work with you.

**Comment by MinecraftPublisher** [comment]
Hello there again, What do the lines 11 to 15 of `.env-sample` represent?

**Comment by mhnasajpour** [comment]
Hi. In models we have two types of account: general_user and Business user that we represent them with U and B.
You can change them and those are will be change in database.
I want to say more clearly, all these are to open people's hands for changes, and they are a series of constant variables and you can change them, but I suggest that you do not change the values of lines 11 to 15 at all.
